
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Agreed Fee      <small>Detail Agreed Fee</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/agreed_fee'); ?>">Agreed Fee</a></li>
      <li class="active">Detail</li>
   </ol>
</section>
<style type="text/css">
.form-group {
  width: 50%;
  padding-top:3px;
  padding-bottom: 3px;
  margin-left: 20%!important;
}
.control-label {
  border-right: 1px solid #f4f4f4;
}
.form-group .control-label{
  width: 30%;
}
  .form-group{
    border: 1px solid #f4f4f4;
  }
</style>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">   <?= _ent($BP_Cname); ?><?php echo $BP_Ename; ?></h3>
                     <h5 class="widget-user-desc">Detail</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_agreed_fee" id="form_agreed_fee" >
               <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Patner English Name</label>

                        <div class="col-sm-8">
                           <?php echo $BP_Ename; ?>
                        </div>
                    </div>
              
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PARTNER CODE </label>

                        <div class="col-sm-8">
                           <?= _ent($agreed_fee->CARD_CODE); ?>
                        </div>
                    </div>
                                        

                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CARD TYPE</label>

                        <div class="col-sm-8">
                           <?= _ent($agreed_fee->CLASS_CODE); ?>
                        </div>
                    </div>                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CONTRACT NAME</label>

                        <div class="col-sm-8">
                          
                        </div>
                    </div>        
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TYPE </label>

                        <div class="col-sm-8">
                           <?= _ent($agreed_fee->TYPE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">MED DAYS </label>

                        <div class="col-sm-8">
                           <?= _ent($agreed_fee->MED_DAYS); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CO PAY </label>

                        <div class="col-sm-8">
                           <?= _ent($agreed_fee->CO_PAY); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">FEE </label>

                        <div class="col-sm-8">
                           <?= _ent($agreed_fee->FEE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PAY </label>

                        <div class="col-sm-8">
                           <?= _ent($agreed_fee->PAY); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">EXTRA MED</label>

                        <div class="col-sm-8">
                           <?php if ($agreed_fee->EXTRA_MED_BOL ==1) {
                                 echo '<input type="checkbox" class="largeCheck" name="EXTRA_MED_BOL" checked>';
                               } 
                                else{
                                    echo '<input type="checkbox"  class="largeCheck" name="EXTRA_MED_BOL">';
                                } ?> 
                            </div>
                        </div>                                         
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">LAB XRAY</label>

                        <div class="col-sm-8">
                          <?php if ($agreed_fee->LAB_XRAY_BOL ==1) {
                                 echo '<input type="checkbox" name="LAB_XRAY_BOL" checked>';
                               } 
                                else{
                                    echo '<input type="checkbox" name="LAB_XRAY_BOL" >';
                                } ?> 
                        </div>
                    </div>
                                         
     
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">SURGICAL</label>

                        <div class="col-sm-8">
                            <?php if ($agreed_fee->SURGICAL_BOL ==1) {
                                 echo '<input type="checkbox" name="SURGICAL_BOL" checked>';
                               } 
                                else{
                                    echo '<input type="checkbox" name="SURGICAL_BOL" >';
                                } ?>
                        </div>
                    </div>
                                         
          
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CREATOR </label>

                        <div class="col-sm-8">
                           <?= _ent($agreed_fee->CREATOR); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CREATE DATE </label>

                        <div class="col-sm-8">
                           <?= _ent($agreed_fee->CREATE_DATE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">LAST MODIFIER </label>

                        <div class="col-sm-8">
                           <?= _ent($agreed_fee->LAST_MODIFIER); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">LAST UPDATE </label>

                        <div class="col-sm-8">
                           <?= _ent($agreed_fee->LAST_UPDATE); ?>
                        </div>
                    </div>
   
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('agreed_fee_update', function($agreed_fee) use ($agreed_fee){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit agreed_fee (Ctrl+e)" href="<?= site_url('administrator/agreed_fee/edit/'.$agreed_fee->AUTO_NO); ?>"><i class="fa fa-edit" ></i> Edit Agreed Fee</a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/agreed_fee/'); ?>"><i class="fa fa-undo" ></i> Go Agreed Fee List</a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
