
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}

 
jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
     CARD CLASS      <small>Detail Card Class</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/card_class'); ?>">Card Class</a></li>
      <li class="active">Detail</li>
   </ol>
</section>

<style type="text/css">
.form-group {
  width: 50%;
  padding-top:3px;
  padding-bottom: 3px;
  margin-left: 20%!important;
}
.control-label {
  border-right: 1px solid #f4f4f4;
}
.form-group .control-label{
  width: 30%;
}
  .form-group{
    border: 1px solid #f4f4f4;
  }
</style>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"> <?= _ent($card_class->CARD_CODE); ?>  <?= _ent($card_class->CLASS_DESC); ?></h3>
                     <h5 class="widget-user-desc">Detail</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_card_class" id="form_card_class" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CARD CODE </label>

                        <div class="col-sm-8">
                           <?= _ent($card_class->CARD_CODE); ?>
                        </div>
                    </div>
                                         
    
                       <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CARD TYPE</label>

                        <div class="col-sm-8">
                           <?= _ent($card_class->CLASS_CODE); ?>
                        </div>
                    </div>
                       <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Card NAME </label>

                        <div class="col-sm-8">
                           <?= _ent($card_class->CLASS_DESC); ?>
                        </div>
                    </div>
                               <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">STATUS </label>

                        <div class="col-sm-8">
                           <?= _ent($card_class->STATUS); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">START DATE </label>

                        <div class="col-sm-8">
                           <?= _ent($card_class->START_DATE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ORIGINAL TERM DATE </label>

                        <div class="col-sm-8">
                           <?= _ent($card_class->ORIGINAL_TERM_DATE); ?>
                        </div>
                    </div>
                       <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TERM DATE </label>

                        <div class="col-sm-8">
                           <?= _ent($card_class->TERM_DATE); ?>
                        </div>
                    </div>
                                         
         
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">EXTEND CARD </label>

                        <div class="col-sm-8">
                           <?= _ent($card_class->EXTEND_CARD); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">REMARK </label>

                        <div class="col-sm-8">
                           <?= _ent($card_class->REMARK); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CREATOR </label>

                        <div class="col-sm-8">
                           <?= _ent($card_class->CREATOR); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CREATE DATE </label>

                        <div class="col-sm-8">
                           <?= _ent($card_class->CREATE_DATE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">LAST MODIFIER </label>

                        <div class="col-sm-8">
                           <?= _ent($card_class->LAST_MODIFIER); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">LAST UPDATE </label>
                        <div class="col-sm-8">
                           <?= _ent($card_class->LAST_UPDATE); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('card_class_update', function($card_class) use ($card_class){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit card_class (Ctrl+e)" href="<?= site_url('administrator/card_class/edit/' . $card_class->AUTO_NO); ?>"><i class="fa fa-edit" ></i> Edit Partner CARD</a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/card_class/'); ?>"><i class="fa fa-undo" ></i> Go Partner CARD List</a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
