
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<style type="text/css">
.form-group {
  width: 50%;
  padding-top:3px;
  padding-bottom: 3px;
  margin-left: 20%!important;
}
.control-label {
  border-right: 1px solid #f4f4f4;
}
.form-group .control-label{
  width: 30%;
}
  .form-group{
    border: 1px solid #f4f4f4;
  }
</style>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Partner Contact      <small>Detail Partner Contact</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/partner_contact'); ?>">Partner Contact</a></li>
      <li class="active">Detail</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Partner Contact</h3>
                     <h5 class="widget-user-desc">Detail Partner Contact</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_partner_contact" id="form_partner_contact" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">PARTNER CODE </label>

                        <div class="col-sm-8">
                           <?= _ent($partner_contact->CARD_CODE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CONTACT NO </label>

                        <div class="col-sm-8">
                           <?= _ent($partner_contact->CONTACT_NO); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">E NAME </label>

                        <div class="col-sm-8">
                           <?= _ent($partner_contact->E_NAME); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">C NAME </label>

                        <div class="col-sm-8">
                           <?= _ent($partner_contact->C_NAME); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TITLE </label>

                        <div class="col-sm-8">
                           <?= _ent($partner_contact->TITLE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">DEPARTMENT </label>

                        <div class="col-sm-8">
                           <?= _ent($partner_contact->DEPARTMENT); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">TEL </label>

                        <div class="col-sm-8">
                           <?= _ent($partner_contact->TEL); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">FAX </label>

                        <div class="col-sm-8">
                           <?= _ent($partner_contact->FAX); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">EMAIL </label>

                        <div class="col-sm-8">
                           <?= _ent($partner_contact->EMAIL); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CREATOR </label>

                        <div class="col-sm-8">
                           <?= _ent($partner_contact->CREATOR); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">CREATE DATE </label>

                        <div class="col-sm-8">
                           <?= _ent($partner_contact->CREATE_DATE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">LAST MODIFIER </label>

                        <div class="col-sm-8">
                           <?= _ent($partner_contact->LAST_MODIFIER); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">LAST UPDATE </label>

                        <div class="col-sm-8">
                           <?= _ent($partner_contact->LAST_UPDATE); ?>
                        </div>
                    </div>
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('partner_contact_update', function($partner_contact) use ($partner_contact){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit partner_contact (Ctrl+e)" href="<?= site_url('administrator/partner_contact/edit/'.$partner_contact->CARD_CODE.'/'.$partner_contact->CONTACT_NO); ?>"><i class="fa fa-edit" ></i> Edit Partner Contact</a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/partner_contact/'); ?>"><i class="fa fa-undo" ></i> Go Partner Contact List</a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
