
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Partner_contact/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Partner Contact<small>List All</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Partner Contact</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('partner_contact_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="add new Partner Contact (Ctrl+a)" href="<?=  site_url('administrator/partner_contact/add'); ?>"><i class="fa fa-plus-square-o" ></i> Add New Partner Contact</a>
                        <?php }) ?>
                        <?php is_allowed('partner_contact_export', function(){?>
                        <a class="btn btn-flat btn-success" title="export Partner Contact" href="<?= site_url('administrator/partner_contact/export'); ?>"><i class="fa fa-file-excel-o" ></i> Export XLS</a>
                        <?php }) ?>
                        <?php is_allowed('partner_contact_export', function(){?>
                        <a class="btn btn-flat btn-success" title="export pdf Partner Contact" href="<?= site_url('administrator/partner_contact/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> Export PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Partner Contact</h3>
                     <h5 class="widget-user-desc">List All Partner Contact <i class="label bg-yellow"><?= $partner_contact_counts; ?>  items</i></h5>
                  </div>

                  <form name="form_partner_contact" id="form_partner_contact" action="<?= base_url('administrator/partner_contact/index'); ?>">
                  
                           <div class="row" style="margin-bottom: 5PX;">
                  <div class="col-md-8">
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="Filter" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value="">All</option>
                            <option <?= $this->input->get('f') == 'CARD_CODE' ? 'selected' :''; ?> value="CARD_CODE">PARTNER CODE</option>
                           <option <?= $this->input->get('f') == 'CONTACT_NO' ? 'selected' :''; ?> value="CONTACT_NO">CONTACT NO</option>
                           <option <?= $this->input->get('f') == 'E_NAME' ? 'selected' :''; ?> value="E_NAME">E NAME</option>
                           <option <?= $this->input->get('f') == 'C_NAME' ? 'selected' :''; ?> value="C_NAME">C NAME</option>
                           <option <?= $this->input->get('f') == 'TITLE' ? 'selected' :''; ?> value="TITLE">TITLE</option>
                           <option <?= $this->input->get('f') == 'DEPARTMENT' ? 'selected' :''; ?> value="DEPARTMENT">DEPARTMENT</option>
                           <option <?= $this->input->get('f') == 'TEL' ? 'selected' :''; ?> value="TEL">TEL</option>
                           <option <?= $this->input->get('f') == 'FAX' ? 'selected' :''; ?> value="FAX">FAX</option>
                           <option <?= $this->input->get('f') == 'EMAIL' ? 'selected' :''; ?> value="EMAIL">EMAIL</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="filter search">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/partner_contact');?>" title="reset filters">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                                   <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>PARTNER CODE</th>
                           <th>CONTACT NO</th>
                           <th>ENG NAME</th>
                           <th>CHI NAME</th>
                           <th>TITLE</th>
                           <th>DEPARTMENT</th>
                           <th>TEL</th>
                           <th>FAX</th>
                           <th>EMAIL</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_partner_contact">
                     <?php foreach($partner_contacts as $partner_contact): ?>
                        <tr>
                           <td><?= _ent($partner_contact->CARD_CODE); ?></td> 
                           <td><?= _ent($partner_contact->CONTACT_NO); ?></td> 
                           <td><?= _ent($partner_contact->E_NAME); ?></td> 
                           <td><?= _ent($partner_contact->C_NAME); ?></td> 
                           <td><?= _ent($partner_contact->TITLE); ?></td> 
                           <td><?= _ent($partner_contact->DEPARTMENT); ?></td> 
                           <td><?= _ent($partner_contact->TEL); ?></td> 
                           <td><?= _ent($partner_contact->FAX); ?></td> 
                           <td><?= _ent($partner_contact->EMAIL); ?></td> 
                           <td width="200">
                              <?php is_allowed('partner_contact_view', function($partner_contact) use ($partner_contact){?>
                              <a href="<?= site_url('administrator/partner_contact/view/' . $partner_contact->CARD_CODE.'/'.$partner_contact->CONTACT_NO); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> View
                              <?php }) ?>
                              <?php is_allowed('partner_contact_update', function($partner_contact) use ($partner_contact){?>
                              <a href="<?= site_url('administrator/partner_contact/edit/' .  $partner_contact->CARD_CODE.'/'.$partner_contact->CONTACT_NO); ?>" class="label-default"><i class="fa fa-edit "></i> Update</a>
                              <?php }) ?>
                              <?php is_allowed('partner_contact_delete', function($partner_contact) use ($partner_contact){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/partner_contact/delete/' . $partner_contact->CARD_CODE.'/'. $partner_contact->CONTACT_NO); ?>" class="label-default remove-data"><i class="fa fa-close"></i> Remove</a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($partner_contact_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Partner Contact data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
        
               </form> 
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "Are you sure?",
          text: "data to be deleted can not be restored!",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Yes, delete it!",
          cancelButtonText: "No, cancel plx!",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_partner_contact').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "Are you sure?",
            text: "data to be deleted can not be restored!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel plx!",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/partner_contact/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "Please choose bulk action first!",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>