
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Staff_payment/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Staff Payment<small>List All</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Staff Payment</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('staff_payment_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="add new Staff Payment (Ctrl+a)" href="<?=  site_url('administrator/staff_payment/add'); ?>"><i class="fa fa-plus-square-o" ></i> Add New Staff Payment</a>
                        <?php }) ?>
                        <?php is_allowed('staff_payment_export', function(){?>
                        <a class="btn btn-flat btn-success" title="export Staff Payment" href="<?= site_url('administrator/staff_payment/export'); ?>"><i class="fa fa-file-excel-o" ></i> Export XLS</a>
                        <?php }) ?>
                        <?php is_allowed('staff_payment_export', function(){?>
                        <a class="btn btn-flat btn-success" title="export pdf Staff Payment" href="<?= site_url('administrator/staff_payment/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> Export PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Staff Payment</h3>
                     <h5 class="widget-user-desc">List All Staff Payment <i class="label bg-yellow"><?= $staff_payment_counts; ?>  items</i></h5>
                  </div>

                  <form name="form_staff_payment" id="form_staff_payment" action="<?= base_url('administrator/staff_payment/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                           <th>STAFF CODE</th>
                           <th>PAYEE NAME</th>
                           <th>PAYEE ADDR1</th>
                           <th>PAYEE ADDR2</th>
                           <th>PAYEE ADDR3</th>
                           <th>PAYEE ADDR4</th>
                           <th>PAYEE ADDR5</th>
                           <th>PAYEE DISTRICT</th>
                           <th>BANK CLEARING CODE</th>
                           <th>ACCOUNT NO</th>
                           <th>ACCOUNT HOLDER</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_staff_payment">
                     <?php foreach($staff_payments as $staff_payment): ?>
                        <tr>
                           <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $staff_payment->STAFF_CODE; ?>">
                           </td>
                           
                           <td><?= _ent($staff_payment->STAFF_CODE); ?></td> 
                           <td><?= _ent($staff_payment->PAYEE_NAME); ?></td> 
                           <td><?= _ent($staff_payment->PAYEE_ADDR1); ?></td> 
                           <td><?= _ent($staff_payment->PAYEE_ADDR2); ?></td> 
                           <td><?= _ent($staff_payment->PAYEE_ADDR3); ?></td> 
                           <td><?= _ent($staff_payment->PAYEE_ADDR4); ?></td> 
                           <td><?= _ent($staff_payment->PAYEE_ADDR5); ?></td> 
                           <td><?= _ent($staff_payment->PAYEE_DISTRICT); ?></td> 
                           <td><?= _ent($staff_payment->BANK_CLEARING_CODE); ?></td> 
                           <td><?= _ent($staff_payment->ACCOUNT_NO); ?></td> 
                           <td><?= _ent($staff_payment->ACCOUNT_HOLDER); ?></td> 
                           <td width="200">
                              <?php is_allowed('staff_payment_view', function($staff_payment) use ($staff_payment){?>
                              <a href="<?= site_url('administrator/staff_payment/view/' . $staff_payment->STAFF_CODE); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> View
                              <?php }) ?>
                              <?php is_allowed('staff_payment_update', function($staff_payment) use ($staff_payment){?>
                              <a href="<?= site_url('administrator/staff_payment/edit/' . $staff_payment->STAFF_CODE); ?>" class="label-default"><i class="fa fa-edit "></i> Update</a>
                              <?php }) ?>
                              <?php is_allowed('staff_payment_delete', function($staff_payment) use ($staff_payment){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/staff_payment/delete/' . $staff_payment->STAFF_CODE); ?>" class="label-default remove-data"><i class="fa fa-close"></i> Remove</a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($staff_payment_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Staff Payment data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="apply bulk actions">Apply</button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="Filter" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value="">All</option>
                            <option <?= $this->input->get('f') == 'STAFF_CODE' ? 'selected' :''; ?> value="STAFF_CODE">STAFF CODE</option>
                           <option <?= $this->input->get('f') == 'PAYEE_NAME' ? 'selected' :''; ?> value="PAYEE_NAME">PAYEE NAME</option>
                           <option <?= $this->input->get('f') == 'PAYEE_ADDR1' ? 'selected' :''; ?> value="PAYEE_ADDR1">PAYEE ADDR1</option>
                           <option <?= $this->input->get('f') == 'PAYEE_ADDR2' ? 'selected' :''; ?> value="PAYEE_ADDR2">PAYEE ADDR2</option>
                           <option <?= $this->input->get('f') == 'PAYEE_ADDR3' ? 'selected' :''; ?> value="PAYEE_ADDR3">PAYEE ADDR3</option>
                           <option <?= $this->input->get('f') == 'PAYEE_ADDR4' ? 'selected' :''; ?> value="PAYEE_ADDR4">PAYEE ADDR4</option>
                           <option <?= $this->input->get('f') == 'PAYEE_ADDR5' ? 'selected' :''; ?> value="PAYEE_ADDR5">PAYEE ADDR5</option>
                           <option <?= $this->input->get('f') == 'PAYEE_DISTRICT' ? 'selected' :''; ?> value="PAYEE_DISTRICT">PAYEE DISTRICT</option>
                           <option <?= $this->input->get('f') == 'BANK_CLEARING_CODE' ? 'selected' :''; ?> value="BANK_CLEARING_CODE">BANK CLEARING CODE</option>
                           <option <?= $this->input->get('f') == 'ACCOUNT_NO' ? 'selected' :''; ?> value="ACCOUNT_NO">ACCOUNT NO</option>
                           <option <?= $this->input->get('f') == 'ACCOUNT_HOLDER' ? 'selected' :''; ?> value="ACCOUNT_HOLDER">ACCOUNT HOLDER</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="filter search">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/staff_payment');?>" title="reset filters">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "Are you sure?",
          text: "data to be deleted can not be restored!",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Yes, delete it!",
          cancelButtonText: "No, cancel plx!",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_staff_payment').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "Are you sure?",
            text: "data to be deleted can not be restored!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel plx!",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/staff_payment/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "Please choose bulk action first!",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>