<style type="text/css">
  .tab-pane {
    padding: 10px 0;
  }
  .legend-title {
    margin-bottom: 30px;
  }
   .legend-title .title {
    background: #fff;
    font-size: 18px;
    position: relative;
    padding: 0 10px;
    bottom: -13px;
    color: #646464;
    text-decoration: underline;
   }
   .legend-title b {
    color: #6CA45B
   }
</style>
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/permission/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+s', function assets() {
       $('#btn_save').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
        if ($('#btn_undo').is(":visible")) {
          $('#btn_undo').trigger('click');
        }
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Setting
      <small>List All</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Setting</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Setting</h3>
                     <h5 class="widget-user-desc">Web Settings</h5>
                  </div>
                </div>

                    <div class="row-fluid">
                      <!-- Custom Tabs -->
                      <div class="nav-tabs-custom">
                        <ul class="nav nav-tabs">
                          <li class="active"><a href="#tab_general" class="tab_group" data-toggle="tab"><i class="fa fa-compass text-green"></i> Site General</a></li>
                          <li class=""><a href="#tab_system" class="tab_group" data-toggle="tab"><i class="fa fa-tv text-green"></i> System</a></li>
                       
                          
                        </ul>
                       <?= form_open('administrator/setting/save', [
                          'name'    => 'form_setting', 
                          'class'   => 'form-horizontal', 
                          'id'      => 'form_setting', 
                          'method'  => 'POST'
                        ]); ?>
                        <div class="tab-content">

                          <div class="tab-pane active" id="tab_general">
                            <div class="row">
                              <div class="col-md-6">
                                <div class="col-sm-12">
                                    <label>Site Name <span class="required">*</span></label>
                                    <input type="text" class="form-control" name="site_name" id="site_name" value="<?= get_option('site_name'); ?>">
                                    <small class="info help-block">The site name.</small>
                                </div>

                                <div class="col-sm-12">
                                    <label>Site Description</label>
                                    <textarea type="text" class="form-control" name="site_description" id="site_description" ><?= get_option('site_description'); ?></textarea>
                                    <small class="info help-block">The site meta description.</small>
                                </div>

                                <div class="col-sm-12">
                                      <label>Default landing page <span class="required">*</span></label>
                                      <div class="row">
                                        <div class="col-md-6 ">
                                          <select class="form-control" name="landing_page_id" id="landing_page_id">
                                              <option value="default" >Default theme</option>
                                            <?php foreach ($pages as $page): ?>
                                              <option value="<?= $page->id; ?>" <?= $page->id == get_option('landing_page_id', 'default') ? 'selected' : ''; ?>><?= _ent($page->title); ?></option>
                                            <?php endforeach; ?>
                                          </select>
                                        </div>
                                      </div>
                                      <small class="info help-block">
                                         Default landing page, select from page or default theme.
                                      </small>
                                  </div>

                                <div class="col-sm-12">
                                    <label>Keywords</label>
                                    <textarea type="text" class="form-control" name="keywords" id="keywords" ><?= get_option('keywords'); ?></textarea>
                                    <small class="info help-block">The site meta keywords.</small>
                                </div>

                                <div class="col-sm-12">
                                    <label>Author</label>
                                    <input type="text" class="form-control" name="author" id="author" value="<?= get_option('author'); ?>">
                                    <small class="info help-block">The author name.</small>
                                </div>

                                <div class="col-sm-12">
                                    <label>Email <span class="required">*</span></label>
                                    <input type="text" class="form-control" name="email" id="email"value="<?= get_option('email'); ?>">
                                    <small class="info help-block">The email of user author.</small>
                                </div>
                              </div>
                            </div>
                          </div>
                          <!-- /.tab-pane -->

                          <div class="tab-pane " id="tab_system">
                            <div class="row">
                              <div class="col-md-12">
                                 <div class="panel-group" id="accordion">
                                    <div class="panel panel-default">
                                      <div class="panel-heading">
                                        <h4 class="panel-title">
                                          <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                                          <b class="text-green">Session</b> Configuration</a>
                                        </h4>
                                      </div>
                                      <div id="collapse1" class="panel-collapse collapse in">
                                        <div class="panel-body">

                                        <!-- start content -->
                                        <div class="row col-md-6">
                                          <div class="col-sm-12">
                                              <label>Session Cookie Name <span class="required">*</span></label>
                                              <input type="text" class="form-control" name="sess_cookie_name" id="sess_cookie_name" value="<?= $this->config->item('sess_cookie_name'); ?>">
                                              <small class="info help-block">
                                                If you use the Encryption class, you must set an encryption key.
                                              </small>
                                          </div>             

                                          <div class="col-sm-12">
                                              <label>Session Expiration <span class="required">*</span></label>
                                              <div class="row">
                                                <div class="col-md-6 ">
                                                  <select class="form-control " name="sess_expiration" id="sess_expiration">
                                                    <?php foreach ($times as $time): ?>
                                                      <option value="<?= $time['value']; ?>" <?= $time['value'] == $this->config->item('sess_expiration') ? 'selected' : ''; ?>><?= $time['label']; ?></option>
                                                    <?php endforeach; ?>
                                                  </select>
                                                </div>
                                              </div>
                                              <small class="info help-block">
                                                 The number you want the session life time.
                                              </small>
                                          </div>    

                                          <div class="col-sm-12">
                                              <label>Session Time to Update <span class="required">*</span></label>
                                              <div class="row">
                                                <div class="col-md-6 ">
                                                  <select class="form-control" name="sess_time_to_update" id="sess_time_to_update">
                                                    <?php foreach ($times as $time): ?>
                                                      <option value="<?= $time['value']; ?>" <?= $time['value'] == $this->config->item('sess_time_to_update') ? 'selected' : ''; ?>><?= $time['label']; ?></option>
                                                    <?php endforeach; ?>
                                                  </select>
                                                </div>
                                              </div>
                                              <small class="info help-block">
                                                 How many time between regenerating the session ID.
                                              </small>
                                          </div>

                                          <div class="col-sm-12">
                                              <label>Session Cookie Name <span class="required">*</span></label>
                                              <input type="text" class="form-control" name="sess_cookie_name" id="sess_cookie_name" value="<?= $this->config->item('sess_cookie_name'); ?>">
                                              <small class="info help-block">
                                                 The session cookie name.
                                              </small>
                                          </div>
                                        </div>
                                        <!-- end content -->
                                        </div>
                                      </div>
                                    </div>

                                    <div class="panel panel-default">
                                      <div class="panel-heading">
                                        <h4 class="panel-title">
                                          <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
                                          <b class="text-green">CSRF</b> Configuration</a>
                                        </h4>
                                      </div>
                                      <div id="collapse2" class="panel-collapse collapse">
                                        <div class="panel-body">
                                          <!-- start content -->
                                            <div class="row col-md-6">
                                            <div class="col-sm-12">
                                                <label>CSRF Token Name <span class="required">*</span></label>
                                                <input type="text" class="form-control" name="csrf_token_name" id="csrf_token_name" value="<?= $this->config->item('csrf_token_name'); ?>">
                                                <small class="info help-block">
                                                   The token name.
                                                </small>
                                            </div>             

                                            <div class="col-sm-12">
                                                <label>CSRF Cookie Name <span class="required">*</span></label>
                                                <input type="text" class="form-control" name="csrf_cookie_name" id="csrf_cookie_name" value="<?= $this->config->item('csrf_cookie_name'); ?>">
                                                <small class="info help-block">
                                                   The cookie name.
                                                </small>
                                            </div>    

                                            <div class="col-sm-12">
                                                <label>CSRF Expire <span class="required">*</span></label>
                                                <div class="row">
                                                  <div class="col-md-6 ">
                                                    <select class="form-control" name="csrf_expire" id="csrf_expire">
                                                      <?php foreach ($times as $time): ?>
                                                        <option value="<?= $time['value']; ?>" <?= $time['value'] == $this->config->item('csrf_expire') ? 'selected' : ''; ?>><?= $time['label']; ?></option>
                                                      <?php endforeach; ?>
                                                    </select>
                                                  </div>
                                                </div>
                                                <small class="info help-block">
                                                   The number the token should expire.
                                                </small>
                                            </div>    

                                            </div>
                                          <!-- end content -->
                                        </div>
                                      </div>
                                    </div>
                                    <div class="panel panel-default">
                                      <div class="panel-heading">
                                        <h4 class="panel-title">
                                          <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
                                          <b class="text-green">Other</b> Configuration</a>
                                        </h4>
                                      </div>
                                      <div id="collapse3" class="panel-collapse collapse">
                                        <div class="panel-body">
                                          <div class="row col-md-6">
                                            <!-- start content -->
                                              <div class="col-sm-12">
                                                  <label>Permitted URI Chars </label>
                                                  <input type="text" class="form-control" name="permitted_uri_chars" id="permitted_uri_chars" value="<?= $this->config->item('permitted_uri_chars'); ?>">
                                                  <small class="info help-block">
                                                    The configured value is actually a regular expression character group and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
                                                  </small>
                                              </div>

                                              <div class="col-sm-12">
                                                  <label>URL Suffix </label>
                                                  <input type="text" class="form-control" name="url_suffix" id="url_suffix" value="<?= $this->config->item('url_suffix'); ?>">
                                                  <small class="info help-block">
                                                    This option allows you to add a suffix to all URLs generated.
                                                    <br> Example : http://example.com/blog/article-1<b class="text-danger tip" title=".html is URL Suffix ">.html</b>
                                                  </small>
                                              </div>

                                              <div class="col-sm-12">
                                                  <label> Global XSS Filtering <i class="required">*</i></label>
                                                  <div class="row">
                                                    <div class="col-md-6 ">
                                                      <select class="form-control" name="global_xss_filtering" id="global_xss_filtering" placeholder="Global XSS Filtering">
                                                      <?php
                                                      $global_xss_filtering = $this->config->item('global_xss_filtering');
                                                      ?>
                                                        <option value="TRUE" <?= $global_xss_filtering == TRUE ? 'selected' :'' ; ?>>YES</option>
                                                        <option value="FALSE" <?= $global_xss_filtering == FALSE ? 'selected' :'' ; ?>>NO</option>
                                                      </select>
                                                    </div>
                                                  </div>
                                                   <small class="info help-block">
                                                    Determines whether the XSS filter is always active when GET, POST or COOKIE data is encountered
                                                  </small>
                                                </div>

                                              <div class="col-sm-12">
                                                  <label>Encryption Key <span class="required">*</span></label>
                                                  <input type="text" class="form-control" name="encryption_key" id="encryption_key" value="<?= $this->config->item('encryption_key'); ?>">
                                                  <small class="info help-block">
                                                    If you use the Encryption class, you must set an encryption key.
                                                  </small>
                                              </div>
                                            <!-- end content -->
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div> 
                              </div>

                            </div>
                          </div>
                          <!-- end tab pane -->
                        </div>
                        <!-- /.tab-content -->
                      </div>
                      <!-- nav-tabs-custom -->
                    <div class="message no-message-padding">
                      
                    </div>
                        <?php is_allowed('setting_update', function(){?>
                        <button class="btn btn-flat btn-default btn_save btn_action" id="btn_save" data-stype='stay' title="save (Ctrl+s)"><i class="fa fa-save" ></i> Save</button>
                        <?php }) ?>
                         <span class="loading loading-hide"><img src="<?= BASE_ASSET; ?>/img/loading-spin-primary.svg"> <i>Loading data</i></span>

                        <a class="btn btn-flat btn-default btn_undo" data-id="0" id="btn_undo" title="undo (Ctrl+x)" style="display: none;"><i class="fa fa-undo" ></i> Undo</a>
                    <?= form_close(); ?>
                    </div>
                    <!-- /.col -->
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->



<!-- Page script -->
<script>
  $(document).ready(function() {
     $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
         checkboxClass: 'icheckbox_flat-green',
         radioClass: 'iradio_flat-green'
     });

     $('.btn_save').click(function() {
         $('.message').fadeOut();

         var form_setting = $('#form_setting');
         var data_post = form_setting.serialize();

         $('.loading').show();

         $.ajax({
                 url: BASE_URL + '/administrator/setting/save',
                 type: 'POST',
                 dataType: 'json',
                 data: data_post,
             })
             .done(function(res) {
                 if (res.success) {
                     $('.message').printMessage({
                         message: res.message
                     });
                     $('.message').fadeIn();
                     $('.btn_undo').hide();

                 } else {
                     $('.message').printMessage({
                         message: res.message,
                         type: 'warning'
                     });
                     $('.message').fadeIn();
                 }

             })
             .fail(function() {
                 $('.message').printMessage({
                     message: 'Error save data',
                     type: 'warning'
                 });
             })
             .always(function() {
                 $('.loading').hide();
                 $('html, body').animate({
                     scrollTop: $(document).height()
                 }, 1000);
             });

         return false;
     }); /*end btn save*/

 }); /*end doc ready*/
</script>