
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<style type="text/css">
.form-group {
  width: 50%;
  padding-top:3px;
  padding-bottom: 3px;
  margin-left: 20%!important;
}
.control-label {
  border-right: 1px solid #f4f4f4;
}
.form-group .control-label{
  width: 30%;
}
  .form-group{
    border: 1px solid #f4f4f4;
  }
</style>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Doctor Type Desc      <small>Detail Doctor Type Desc</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/doctor_type_desc'); ?>">Doctor Type Desc</a></li>
      <li class="active">Detail</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Doctor Type Desc</h3>
                     <h5 class="widget-user-desc">Detail Doctor Type Desc</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_doctor_type_desc" id="form_doctor_type_desc" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Doctor Type Code </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_type_desc->DT_CODE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">English Description </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_type_desc->E_DESC); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Creator </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_type_desc->CREATOR); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Create Date </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_type_desc->CREATE_DATE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Last Modifier </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_type_desc->LAST_MODIFIER); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Last Update </label>

                        <div class="col-sm-8">
                           <?= _ent($doctor_type_desc->LAST_UPDATE); ?>
                        </div>
                    </div>
                                         
                    
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('doctor_type_desc_update', function($doctor_type_desc) use ($doctor_type_desc){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit doctor_type_desc (Ctrl+e)" href="<?= site_url('administrator/doctor_type_desc/edit/'.$doctor_type_desc->DT_CODE); ?>"><i class="fa fa-edit" ></i> Edit Doctor Type Desc</a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/doctor_type_desc/'); ?>"><i class="fa fa-undo" ></i> Go Doctor Type Desc List</a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
