
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Class Fee      <small>Detail Class Fee</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/class_fee'); ?>">Class Fee</a></li>
      <li class="active">Detail</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Class Fee</h3>
                     <h5 class="widget-user-desc">Detail Class Fee</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_class_fee" id="form_class_fee" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Company Code </label>

                        <div class="col-sm-8">
                           <?= _ent($class_fee->COMPANY_CODE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Class Code </label>

                        <div class="col-sm-8">
                           <?= _ent($class_fee->CLASS_CODE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Type </label>

                        <div class="col-sm-8">
                           <?= _ent($class_fee->TYPE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Med Days </label>

                        <div class="col-sm-8">
                           <?= _ent($class_fee->MED_DAYS); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Co Pay </label>

                        <div class="col-sm-8">
                           <?= _ent($class_fee->CO_PAY); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Fee </label>

                        <div class="col-sm-8">
                           <?= _ent($class_fee->FEE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Pay </label>

                        <div class="col-sm-8">
                           <?= _ent($class_fee->PAY); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Commission Company </label>

                        <div class="col-sm-8">
                           <?= _ent($class_fee->COMMISSION_COMPANY); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Commission </label>

                        <div class="col-sm-8">
                           <?= _ent($class_fee->COMMISSION); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Extra Med Bol </label>

                        <div class="col-sm-8">
                           <?= _ent($class_fee->EXTRA_MED_BOL); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Lab Xray Bol </label>

                        <div class="col-sm-8">
                           <?= _ent($class_fee->LAB_XRAY_BOL); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Surgical Bol </label>

                        <div class="col-sm-8">
                           <?= _ent($class_fee->SURGICAL_BOL); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('class_fee_update', function($class_fee) use ($class_fee){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit class_fee (Ctrl+e)" href="<?= site_url('administrator/class_fee/edit/'.$class_fee->MED_DAYS); ?>"><i class="fa fa-edit" ></i> Edit Class Fee</a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/class_fee/'); ?>"><i class="fa fa-undo" ></i> Go Class Fee List</a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
