
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Class_fee/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Class Fee<small>List All</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Class Fee</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('class_fee_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="add new Class Fee (Ctrl+a)" href="<?=  site_url('administrator/class_fee/add'); ?>"><i class="fa fa-plus-square-o" ></i> Add New Class Fee</a>
                        <?php }) ?>
                        <?php is_allowed('class_fee_export', function(){?>
                        <a class="btn btn-flat btn-success" title="export Class Fee" href="<?= site_url('administrator/class_fee/export'); ?>"><i class="fa fa-file-excel-o" ></i> Export XLS</a>
                        <?php }) ?>
                        <?php is_allowed('class_fee_export', function(){?>
                        <a class="btn btn-flat btn-success" title="export pdf Class Fee" href="<?= site_url('administrator/class_fee/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> Export PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Class Fee</h3>
                     <h5 class="widget-user-desc">List All Class Fee <i class="label bg-yellow"><?= $class_fee_counts; ?>  items</i></h5>
                  </div>

                  <form name="form_class_fee" id="form_class_fee" action="<?= base_url('administrator/class_fee/index'); ?>">
                  

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
							<th>Company Code</th>
							<th>Class Code</th>
						   <th>Type</th>
						   <th>Med Days</th>
						   <th>Co Pay</th>
						   <th>Fee</th>
						   <th>Pay</th>
						   <th>Commission Company</th>
						   <th>Commission</th>
						   <th>Extra Med Bol</th>
						   <th>Lab Xray Bol</th>
						   <th>Surgical Bol</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_class_fee">
                     <?php foreach($class_fees as $class_fee): ?>
                        <tr>
							<td><?= _ent($class_fee->COMPANY_CODE); ?></td>
							<td><?= _ent($class_fee->CLASS_CODE); ?></td>
							<td><?= _ent($class_fee->TYPE); ?></td>
							<td><?= _ent($class_fee->MED_DAYS); ?></td>
							<td><?= _ent($class_fee->CO_PAY); ?></td>
							<td><?= _ent($class_fee->FEE); ?></td>
							<td><?= _ent($class_fee->PAY); ?></td>
							<td><?= _ent($class_fee->COMMISSION_COMPANY); ?></td>
							<td><?= _ent($class_fee->COMMISSION); ?></td>
							<td><?php if (_ent($class_fee->EXTRA_MED_BOL) == 1){ echo "<p style='color:green;'>True</p>"; }else{ echo "<p style='color:red;'>False</p>"; } ?></td>
							<td><?php if (_ent($class_fee->LAB_XRAY_BOL) == 1){ echo "<p style='color:green;'>True</p>"; }else{ echo "<p style='color:red;'>False</p>"; } ?></td>
							<td><?php if (_ent($class_fee->SURGICAL_BOL) == 1){ echo "<p style='color:green;'>True</p>"; }else{ echo "<p style='color:red;'>False</p>"; } ?></td>
                           <td width="200">
                              <?php is_allowed('class_fee_view', function($class_fee) use ($class_fee){?>
                              <a href="<?= site_url('administrator/class_fee/view/' . $class_fee->CLASS_FEE_CODE); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> View
                              <?php }) ?>
                              <?php is_allowed('class_fee_update', function($class_fee) use ($class_fee){?>
                              <a href="<?= site_url('administrator/class_fee/edit/' . $class_fee->CLASS_FEE_CODE); ?>" class="label-default"><i class="fa fa-edit "></i> Update</a>
                              <?php }) ?>
                              <?php is_allowed('class_fee_delete', function($class_fee) use ($class_fee){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/class_fee/delete/' . $class_fee->CLASS_FEE_CODE); ?>" class="label-default remove-data"><i class="fa fa-close"></i> Remove</a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($class_fee_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Class Fee data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               <div class="row">
                  <div class="col-md-8">
                     <div class="col-sm-2 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                           <option value="">Bulk</option>
                           <option value="delete">Delete</option>
                        </select>
                     </div>
                     <div class="col-sm-2 padd-left-0 ">
                        <button type="button" class="btn btn-flat" name="apply" id="apply" title="apply bulk actions">Apply</button>
                     </div>
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="Filter" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value="">All</option>
                            <option <?= $this->input->get('f') == 'CO_PAY' ? 'selected' :''; ?> value="CO_PAY">CO PAY</option>
                           <option <?= $this->input->get('f') == 'FEE' ? 'selected' :''; ?> value="FEE">FEE</option>
                           <option <?= $this->input->get('f') == 'PAY' ? 'selected' :''; ?> value="PAY">PAY</option>
                           <option <?= $this->input->get('f') == 'COMMISION_COMPANY' ? 'selected' :''; ?> value="COMMISION_COMPANY">COMMISION COMPANY</option>
                           <option <?= $this->input->get('f') == 'COMMISION' ? 'selected' :''; ?> value="COMMISION">COMMISION</option>
                           <option <?= $this->input->get('f') == 'EXTRA_MED_BOL' ? 'selected' :''; ?> value="EXTRA_MED_BOL">EXTRA MED BOL</option>
                           <option <?= $this->input->get('f') == 'LAB_XRAY_BOL' ? 'selected' :''; ?> value="LAB_XRAY_BOL">LAB XRAY BOL</option>
                           <option <?= $this->input->get('f') == 'SURGICAL_BOL' ? 'selected' :''; ?> value="SURGICAL_BOL">SURGICAL BOL</option>
                           <option <?= $this->input->get('f') == 'REMARK' ? 'selected' :''; ?> value="REMARK">REMARK</option>
                           <option <?= $this->input->get('f') == 'EXPIRY' ? 'selected' :''; ?> value="EXPIRY">EXPIRY</option>
                           <option <?= $this->input->get('f') == 'UDF1' ? 'selected' :''; ?> value="UDF1">UDF1</option>
                           <option <?= $this->input->get('f') == 'UDF2' ? 'selected' :''; ?> value="UDF2">UDF2</option>
                           <option <?= $this->input->get('f') == 'UDF3' ? 'selected' :''; ?> value="UDF3">UDF3</option>
                           <option <?= $this->input->get('f') == 'UDF4' ? 'selected' :''; ?> value="UDF4">UDF4</option>
                           <option <?= $this->input->get('f') == 'UDF5' ? 'selected' :''; ?> value="UDF5">UDF5</option>
                           <option <?= $this->input->get('f') == 'LAST_MODIFIER' ? 'selected' :''; ?> value="LAST_MODIFIER">LAST MODIFIER</option>
                           <option <?= $this->input->get('f') == 'LAST_UPDATE' ? 'selected' :''; ?> value="LAST_UPDATE">LAST UPDATE</option>
                          </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="filter search">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/class_fee');?>" title="reset filters">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                  </form>                  <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "Are you sure?",
          text: "data to be deleted can not be restored!",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Yes, delete it!",
          cancelButtonText: "No, cancel plx!",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_class_fee').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "Are you sure?",
            text: "data to be deleted can not be restored!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel plx!",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/class_fee/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "Please choose bulk action first!",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>