
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      $('#btn_back').trigger('click');
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Staff      <small>Detail Staff</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/staff'); ?>">Staff</a></li>
      <li class="active">Detail</li>
   </ol>
</section>
<style type="text/css">
.form-group {
  width: 50%;
  padding-top:5px;
  padding-bottom: 5px;
  margin-left: 20%!important;
}
.control-label {
  border-right: 1px solid #f4f4f4;
}
.form-group .control-label{
  width: 30%;
}
  .form-group{
    border: 1px solid #f4f4f4;
  }
</style>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">

               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                    
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/view.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username"><?= _ent($staff->STAFF_CODE); ?></h3>
                     <h5 class="widget-user-desc">Detail</h5>
                     <hr>
                  </div>

                 
                  <div class="form-horizontal" name="form_staff" id="form_staff" >
                   
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Staff Code </label>

                        <div class="col-sm-8">
                           <?= _ent($staff->STAFF_CODE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">English Name </label>

                        <div class="col-sm-8">
                           <?= _ent($staff->E_NAME); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Chinese Name </label>

                        <div class="col-sm-8">
                           <?= _ent($staff->C_NAME); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Phone </label>

                        <div class="col-sm-8">
                           <?= _ent($staff->PHONE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Email </label>

                        <div class="col-sm-8">
                           <?= _ent($staff->EMAIL); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Password </label>

                        <div class="col-sm-8">
                           <?= _ent($staff->PWD); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Role code </label>

                        <div class="col-sm-8">
                           <?= _ent($staff->ROLE_CODE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Status </label>

                        <div class="col-sm-8">
                           <?= _ent($staff->STATUS); ?>
                        </div>
                    </div>
                    <div class="form-group" style="color: #3c6382"><b>Payment:</b></div>

                    <?php if ($staff_payment != null) {
                      echo '
                      <div class="form-group">
                        <label for="content" class="col-sm-2 control-label">Payee Name </label>
                        <div class="col-sm-8">'
                       . $staff_payment->PAYEE_NAME .
                        '</div>
                    </div>
                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Payee Address</label>

                        <div class="col-sm-8">'
                      .$staff_payment->PAYEE_ADDR1 .",". $staff_payment->PAYEE_ADDR2 ."," . $staff_payment->PAYEE_ADDR2 .",".$staff_payment->PAYEE_ADDR3 ."," . $staff_payment->PAYEE_ADDR4 . "," . $staff_payment->PAYEE_ADDR5 . ",".$staff_payment->PAYEE_DISTRICT
                        .'</div>
                    </div>
                      <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Bank Name </label>
                        <div class="col-sm-8">'; 
                          
                           $bank_Code = $staff_payment->BANK_CLEARING_CODE; 
                           $this->db->where("CLEARING_CODE",$bank_Code);
                           $query = $this->db->get("bank");
                            $bank = $query->row_array();
                      echo $bank["C_NAME"]."<br>".$bank["E_NAME"].   
                      '</div>
                    </div>
                      <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ACCOUNT NO </label>
                        <div class="col-sm-8">'
                          .$staff_payment->ACCOUNT_NO.
                       '</div>
                    </div>
                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ACCOUNT HOLDER </label>
                        <div class="col-sm-8">'
                           .$staff_payment->ACCOUNT_HOLDER.
                        '</div>
                    </div
                      ';
                    }else{
                      echo '
                      <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Payee Name </label>

                        <div class="col-sm-8">
                        </div>
                    </div>
                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Payee Address</label>

                        <div class="col-sm-8">
                        </div>
                    </div>
                      <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Bank Name </label>
                        <div class="col-sm-8">
                        </div>
                    </div>
                      <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ACCOUNT NO </label>

                        <div class="col-sm-8">
                        </div>
                    </div>
                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">ACCOUNT HOLDER </label>

                        <div class="col-sm-8">
                        </div>
                    </div
                      ';} ?>
                    <br>
<!--                  <div class="form-group" style="color: #3c6382"><b>Auto Pay:</b></div>
 -->                     <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Creator </label>

                        <div class="col-sm-8">
                           <?= _ent($staff->CREATOR); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Create Date </label>

                        <div class="col-sm-8">
                           <?= _ent($staff->CREATE_DATE); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Last Modifier </label>

                        <div class="col-sm-8">
                           <?= _ent($staff->LAST_MODIFIER); ?>
                        </div>
                    </div>
                                         
                    <div class="form-group ">
                        <label for="content" class="col-sm-2 control-label">Last Update </label>

                        <div class="col-sm-8">
                           <?= _ent($staff->LAST_UPDATE); ?>
                        </div>
                    </div>
                                        
                    <br>
                    <br>

                    <div class="view-nav">
                        <?php is_allowed('staff_update', function($staff) use ($staff){?>
                        <a class="btn btn-flat btn-info btn_edit btn_action" id="btn_edit" data-stype='back' title="edit staff (Ctrl+e)" href="<?= site_url('administrator/staff/edit/'.$staff->STAFF_CODE); ?>"><i class="fa fa-edit" ></i> Edit Staff</a>
                        <?php }) ?>
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/staff/'); ?>"><i class="fa fa-undo" ></i> Go Staff List</a>
                     </div>
                    
                  </div>
               </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
