
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Staff/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Staff<small>List All</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Staff</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('staff_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="add new Staff (Ctrl+a)" href="<?=  site_url('administrator/staff/add'); ?>"><i class="fa fa-plus-square-o" ></i> Add New Staff</a>
                        <?php }) ?>
                        <?php is_allowed('staff_export', function(){?>
                        <a class="btn btn-flat btn-success" title="export Staff" href="<?= site_url('administrator/staff/export'); ?>"><i class="fa fa-file-excel-o" ></i> Export XLS</a>
                        <?php }) ?>
                        <?php is_allowed('staff_export', function(){?>
                        <a class="btn btn-flat btn-success" title="export pdf Staff" href="<?= site_url('administrator/staff/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> Export PDF</a>
                        <?php }) ?>
                     </div>
                     <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div>
                     <!-- /.widget-user-image -->
                     <h3 class="widget-user-username">Staff</h3>
                     <h5 class="widget-user-desc">List All Staff <i class="label bg-yellow"><?= $staff_counts; ?>  items</i></h5>
                  </div>

                  <form name="form_staff" id="form_staff" action="<?= base_url('administrator/staff/index'); ?>">
                  <div class="row" style="margin-bottom: 5px;">
                  <div class="col-md-8">
                     <div class="col-sm-3 padd-left-0  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="Filter" value="<?= $this->input->get('q'); ?>">
                     </div>
                     <div class="col-sm-3 padd-left-0 " >
                        <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                           <option value="">All</option>
                            <option <?= $this->input->get('f') == 'STAFF_CODE' ? 'selected' :''; ?> value="STAFF_CODE">STAFF CODE</option>
                           <option <?= $this->input->get('f') == 'E_NAME' ? 'selected' :''; ?> value="E_NAME">ENG NAME</option>
                           <option <?= $this->input->get('f') == 'C_NAME' ? 'selected' :''; ?> value="C_NAME">CHI NAME</option>
                           <option <?= $this->input->get('f') == 'PHONE' ? 'selected' :''; ?> value="PHONE">PHONE</option>
                           <option <?= $this->input->get('f') == 'EMAIL' ? 'selected' :''; ?> value="EMAIL">EMAIL</option>
                           <option <?= $this->input->get('f') == 'PWD' ? 'selected' :''; ?> value="PWD">PWD</option>
                           <option <?= $this->input->get('f') == 'ROLE_CODE' ? 'selected' :''; ?> value="ROLE_CODE">ROLE CODE</option>
                           <option <?= $this->input->get('f') == 'STATUS' ? 'selected' :''; ?> value="STATUS">STATUS</option>
                       </select>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="filter search">
                        Filter
                        </button>
                     </div>
                     <div class="col-sm-1 padd-left-0 ">
                        <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/staff');?>" title="reset filters">
                        <i class="fa fa-undo"></i>
                        </a>
                     </div>
                  </div>
                           <div class="col-md-4">
                     <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                        <?= $pagination; ?>
                     </div>
                  </div>
               </div>

                  <div class="table-responsive"> 
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                           <th>Staff Code</th>
                           <th>English Name</th>
                           <th>Chinese Name</th>
                           <th>Phone</th>
                           <th>Email</th>
                           <th>Password </th>
                           <th>Role code </th>
                           <th>Status</th>
                           <th>Last Modifier</th>
                           <th>Last Update</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody id="tbody_staff">
                     <?php foreach($staffs as $staff): ?>
                        <tr>
                           <td><?= _ent($staff->STAFF_CODE); ?></td> 
                           <td><?= _ent($staff->E_NAME); ?></td> 
                           <td><?= _ent($staff->C_NAME); ?></td> 
                           <td><?= _ent($staff->PHONE); ?></td> 
                           <td><?= _ent($staff->EMAIL); ?></td> 
                           <td><?= _ent($staff->PWD); ?></td> 
                           <td><?= _ent($staff->ROLE_CODE); ?></td> 
                           <td><?= _ent($staff->STATUS); ?></td> 
                           <td><?= _ent($staff->LAST_MODIFIER); ?></td> 
                           <td><?= _ent($staff->LAST_UPDATE); ?></td> 
                           <td width="200">
                              <?php is_allowed('staff_view', function($staff) use ($staff){?>
                              <a href="<?= site_url('administrator/staff/view/' . $staff->STAFF_CODE); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> View
                              <?php }) ?>
                              <?php is_allowed('staff_update', function($staff) use ($staff){?>
                              <a href="<?= site_url('administrator/staff/edit/' . $staff->STAFF_CODE); ?>" class="label-default"><i class="fa fa-edit "></i> Update</a>
                              <?php }) ?>
                              <?php is_allowed('staff_delete', function($staff) use ($staff){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/staff/delete/' . $staff->STAFF_CODE); ?>" class="label-default remove-data"><i class="fa fa-close"></i> Remove</a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($staff_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Staff data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>
                  </table>
                  </div>
               </div>
               <hr>
               <!-- /.widget-user -->
               
                   </form>     
            </div>
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->
<script>
  $(document).ready(function(){
   
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "Are you sure?",
          text: "data to be deleted can not be restored!",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "Yes, delete it!",
          cancelButtonText: "No, cancel plx!",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_staff').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "Are you sure?",
            text: "data to be deleted can not be restored!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel plx!",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/staff/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "Please choose bulk action first!",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });

  }); /*end doc ready*/
</script>